### ISSUE TITLE
WebGL Build: RuntimeError: null function or function signature mismatch

### ISSUE THREAD

**Issue by The-MAZZTer** [dr-vij/SkiaSharpForUnity#1]
I pulled down this project and did the following:
- Opened in Unity 2021.2.7f1 on Windows 10.
- Removed test framework package (package could not be downloaded and was causing project to open in safe mode)
- Dropped in win64 and win32 native skia libs from nuget for in-editor testing (this caused play mode to work as expected in editor)
- Switched to WebGL build mode
- Built and ran

The following error occurs when the SkiaTest script tries to create the SKBitmap object. I think this is already in libSkiaSharp.a so I assume there's some problem there.

RuntimeError: null function or function signature mismatch
at tt_face_done (http://localhost:8632/Build/Build.wasm:wasm-function[19787]:0x86be24)
    at destroy_face (http://localhost:8632/Build/Build.wasm:wasm-function[11709]:0x47e5ea)
    at FT_Done_Face (http://localhost:8632/Build/Build.wasm:wasm-function[11708]:0x47e482)
    at SkTypeface_FreeType::Scanner::scanFont(SkStreamAsset*, int, SkString*, SkFontStyle*, bool*, SkSTArray<4, SkTypeface_FreeType::Scanner::AxisDefinition, true>*) const (http://localhost:8632/Build/Build.wasm:wasm-function[20270]:0x8b1fd0)
    at EmbeddedSystemFontLoader::loadSystemFonts(SkTypeface_FreeType::Scanner const&, SkTArray<sk_sp<SkFontStyleSet_Custom>, false>*) const (http://localhost:8632/Build/Build.wasm:wasm-function[20305]:0x8b3c37)
    at SkFontMgr::Factory() (http://localhost:8632/Build/Build.wasm:wasm-function[20306]:0x8b41cc)
    at SkFontMgr::RefDefault() (http://localhost:8632/Build/Build.wasm:wasm-function[20311]:0x8b44e2)
    at sk_fontmgr_ref_default (http://localhost:8632/Build/Build.wasm:wasm-function[20373]:0x8b5d63)
    at dynCall_i (http://localhost:8632/Build/Build.wasm:wasm-function[51512]:0x159e6d2)
    at http://localhost:8632/Build/Build.framework.js:1035:20
    at invoke_i (http://localhost:8632/Build/Build.framework.js:16727:10)
    at SkiaApi_sk_fontmgr_ref_default_mC50A359E1C8E61B84FB36B258FD0C922480E2CC9 (http://localhost:8632/Build/Build.wasm:wasm-function[21557]:0x8fe846)
    at GC_call_with_alloc_lock (http://localhost:8632/Build/Build.wasm:wasm-function[1083]:0x648d0)
    at http://localhost:8632/Build/Build.framework.js:1035:20
    at invoke_ii (http://localhost:8632/Build/Build.framework.js:16584:10)
    at SKFontManager__cctor_m11F619CA07BC8C92D3056C5796899FA628F71D7D (http://localhost:8632/Build/Build.wasm:wasm-function[21556]:0x8fe708)
    at RuntimeInvoker_FalseVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*) (http://localhost:8632/Build/Build.wasm:wasm-function[38574]:0xf29c95)
    at il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) (http://localhost:8632/Build/Build.wasm:wasm-function[38739]:0xf2db56)
    at dynCall_iiii (http://localhost:8632/Build/Build.wasm:wasm-function[51510]:0x159e6ba)
    at http://localhost:8632/Build/Build.framework.js:1035:20
    at invoke_iiii (http://localhost:8632/Build/Build.framework.js:16650:10)
    at il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (http://localhost:8632/Build/Build.wasm:wasm-function[38718]:0xf2d01c)
    at il2cpp::vm::Runtime::ClassInit(Il2CppClass*) (http://localhost:8632/Build/Build.wasm:wasm-function[38717]:0xf2ce33)
    at il2cpp_codegen_runtime_class_init_inline(Il2CppClass*) (http://localhost:8632/Build/Build.wasm:wasm-function[36750]:0xf0411b)
    at dynCall_vi (http://localhost:8632/Build/Build.wasm:wasm-function[51514]:0x159e6e4)
    at http://localhost:8632/Build/Build.framework.js:1035:20
    at invoke_vi (http://localhost:8632/Build/Build.framework.js:16606:3)
    at SKObject__cctor_mF41768EF53FFA40A0EDB6E419FD3DD73E10FE0BC (http://localhost:8632/Build/Build.wasm:wasm-function[9730]:0x3a9aa9)
    at RuntimeInvoker_FalseVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*) (http://localhost:8632/Build/Build.wasm:wasm-function[38574]:0xf29c95)
    at il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) (http://localhost:8632/Build/Build.wasm:wasm-function[38739]:0xf2db56)
    at dynCall_iiii (http://localhost:8632/Build/Build.wasm:wasm-function[51510]:0x159e6ba)
    at http://localhost:8632/Build/Build.framework.js:1035:20
    at invoke_iiii (http://localhost:8632/Build/Build.framework.js:16650:10)
    at il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (http://localhost:8632/Build/Build.wasm:wasm-function[38718]:0xf2d01c)
    at il2cpp::vm::Runtime::ClassInit(Il2CppClass*) (http://localhost:8632/Build/Build.wasm:wasm-function[38717]:0xf2ce33)
    at il2cpp_codegen_runtime_class_init_inline(Il2CppClass*) (http://loc

**Comment by dr-vij** [comment]
Same project and code works in unity 2021.1 in development code, so I think problem is inside Unity and dont know how to deal with it now

https://forum.unity.com/threads/null-function-or-function-signature-mismatch-error-and-please-contact-customer-support-message.1192075/#post-7739778

Working example:
https://vij.app/skia-unity-dev/

**Comment by The-MAZZTer** [comment]
I have worked with a friend and we discovered it is a bug in the latest Unity 2021.2. An older version worked for him. So I will need to downgrade or wait for a fix it seems.

**Comment by The-MAZZTer** [comment]
Alright so I tried 2021.2.3 and then 2021.2.2 (as that's the version defined by the repo), Neither worked, same problem as in my original post.

So I tried 2021.1.28 as you described but that won't build at all. The version of emscripten is 1.38.11 which is below the minimum supported version by libSkiaSharp.a (1.39.11). So 2021.1 can't possibly be working. I think maybe you typoed 2021.2?

I'll try 2021.2.3 again tomorrow with a fresh checkout of the repo, not sure what else to try.

**Comment by dr-vij** [comment]
I will create a branch with emscripten version like Unity 2021.1 and check it.

**Comment by The-MAZZTer** [comment]
I checked in 2021.2.3 and it definitely doesn't work, same error as 2021.2.7.

It sounds like you built the .a yourself so you might be able to produce a version that works with Unity 2020/2021.1 (both use 1.38.11). The official nuget package only goes down to 1.39.11 though. But a version usable with 2020 would be helpful (the project I am trying to add WebGL support to currently is on 2020).

Thanks for taking a look at this.

**Comment by dr-vij** [comment]
After long investigation I found a way how to build the library for wasm. the updated library is uploaded. So there is no signature mismatch in 2021.2 version anymore
